### ISSUE TITLE
elastic-ipfs events are delivered to metrics-collector URL (e.g. cf worker)

### ISSUE THREAD

**Issue by gobengo** [elastic-ipfs/metrics-collector#14]
The [metrics-collector MVP](https://github.com/orgs/elastic-ipfs/projects/1) is coming together. The collector itself is deployed. Now we need to get events flowing from elastic-ipfs to the metrics-collector in our staging environments and see it working.

This involves creating/operationalizing https://github.com/elastic-ipfs/event-delivery-lambda

* [x] implement first pass https://github.com/elastic-ipfs/event-delivery-lambda 
* [x] elastic-ipfs infrastructure has a pubsub topic that it can broadcast events to https://github.com/elastic-ipfs/infrastructure/issues/147
* [x] elastic-ipfs infrastructure has a job queue with a job to deliver each event that is published to the events topic https://github.com/elastic-ipfs/infrastructure/issues/147
* [x] deploy event-delivery-lambda to staging https://github.com/elastic-ipfs/event-delivery-lambda/issues/3
* [x] deploy event-delivery-lambda to production
* [x] deploy metrics-collector staging environment https://github.com/elastic-ipfs/metrics-collector/issues/29
* [x] deploy event-delivery-lambda w/ configured user:pass to POST /events on metrics-collector prod
  * https://github.com/elastic-ipfs/event-delivery-lambda/issues/6
* [x] indexer-lambda publishes IndexerCompleted event to SNS topic (and it results in an sqs task, which invokes event-delivery-lambda) https://github.com/elastic-ipfs/indexer-lambda/issues/55
* [x] bucket-to-indexer publishes IndexerNotified event to SNS events topic
  * [x] https://github.com/elastic-ipfs/bucket-to-indexer/pull/11
  * [x] https://github.com/elastic-ipfs/bucket-to-indexer/pull/13

**Comment by gobengo** [comment]
main blocker: https://github.com/elastic-ipfs/event-delivery-lambda/issues/6

**Comment by gobengo** [comment]
confirmed delivery of IndexerNotified and IndexerCompleted events in staging

**Comment by gobengo** [comment]
it's working in prod
